### ISSUE TITLE
Clang builds

### ISSUE THREAD

**Issue by elliottslaughter** [vovkos/llvm-package-windows#1]
Thanks for providing these packages. Would there be any chance of getting Clang builds packaged in the same way?

**Comment by vovkos** [comment]
I planned to originally, but it's not high on the TODO list, sorry. The main reason for me to create this repo in the first place was testing the open-source [Jancy](https://github.com/vovkos/jancy) libraries used in our [IO Ninja](http://ioninja.com/) product -- and Jancy uses the core LLVM libraries, not libclang. So... 

Actually, what I need more is to upgrade this repo (and [llvm-package-travis](https://github.com/vovkos/llvm-package-travis)) for the latest LLVM releases (5, 6). Alas, even with LLVM 4.0 the build process times out quite often -- despite the fact I exclude some unnecessary modules (e.g. PDB and CV stuff on Linux and Mac) by patching the LLVM cmake files. Building LLVM 4 was kinda like rolling a dice -- job timeout, restart, success, timeout, restart, success, etc ;)

Of course, it wouldn't be a problem if I had a paid account without build time-outs, but getting one for handling open-source projects is not reasonable, I hope you understand (and in this case we would need two -- on AppVeyor and Travis).

All that being said, it should be relatively straightforward to create a similar repo for libclang based on this one. There is catch -- building the latest versions of Clang requires pre-built binaries of the latest versions of LLVM, which brings us to the square one :) If, however, you need libclang version 4 or below -- you should be able to reuse the LLVM binaries from this repo (Clang alone is smaller and builds faster than LLVM itself).

**Comment by elliottslaughter** [comment]
Thanks for your response. I'm also looking for something to be used with testing another project, but in my case, I happen to need both libclang and LLVM. My project currently can only handle up to LLVM 3.9, so hopefully build time will not be an issue.

I'm still trying to see if its possible to make the official binaries work, but if I conclude that's not possible, I'll do what you suggest. If I do, would you be interested in hosting that here? I don't know if it's possible to have multiple distinct appveyor scripts in the same repo or not. The main advantage would be avoiding sharding the repo even further. It was already hard enough to find this repo on Google search....

Thanks.

**Comment by vovkos** [comment]
Hosting both LLVM and Clang binaries together totally makes sense, I agree. Alas, it's not easy to achieve technically. 

Each push to a repo triggers a matrix of independent jobs being run on CI servers of AppVeyor (and Travis). Each job in the matrix can be configured independently from others (using env defines) -- so there is no need to have multiple appveyor scripts to produce both LLVM and libclang binaries, a single appveyor.yml with properly configured matrix will do just fine. 

However, we can't make one job to wait for completion of another (or at least I don't know how to do it). In our case, building Clang must be done AFTER building LLVM -- and there is absolutely NO way these two can be put into the same job due to the timeout issue.

Therefore, the most straightforward way would be to have two repos -- one for LLVM, another for libclang. In this case, we can first build the LLVM release, make sure the binaries are available on GitHub releases, and only then push a tagged commit to the libclang repo to trigger the build process for libclang.

**Comment by elliottslaughter** [comment]
I put the code in the Clang branch here: https://github.com/elliottslaughter/llvm-package-windows/tree/clang-3.8.x

And binaries here: https://github.com/elliottslaughter/llvm-package-windows/releases/tag/clang-3.8.1

I was lazy and just did the build in-place by stuffing the Clang source into `llvm/tools/clang`.

By the way, if you ask nicely you can get an increase on the build time for open source projects on AppVeyor. Might be enough to work around your build timeout issues.

**Comment by vovkos** [comment]
Sorry for a late reply Elliott, I was overloaded with Computex 2018-related stuff but now it's finally over :) I checked your commits; to my surprise, you were able to build both Clang and LLVM (with tools, too!) from the same source tree within the alotted 1 hour! Nice! I didn't even hope it could be possible! They must have upgraded their servers recently...

Have you tried building newer versions (LLVM+Clang 4/5/6)?

Good point on trying to ask AppVeyor/Travis for some extra time for this particular project; will do that after running some test builds and estimating how much extra time we need.

**Comment by vovkos** [comment]
Better late than never :D

I have done some major clean-up and update.

- the AppVeyor team graciously increased my allotted time to 1.5 hours;
- tools are now built and included in ``Release`` packages;
- ``llvm-config`` is built and included in ``Debug`` packages, as well;
- ``*.pdb`` are added to ``Debug``  packages;
- Clang (including LibClang) is now built, too;

To make packages for new releases modify ``LLVM_VERSION`` and ``BUILD_PROJECT`` (``llvm`` or ``clang``) in ``.appveyor.yml`` and create a tagged commit.

**Comment by vovkos** [comment]
OK, clang-8.0.0 finished building successfully; closing the issue.
