### ISSUE TITLE
Provide llvm 9.0 (master branch) builds?

### ISSUE THREAD

**Issue by oscarbg** [vovkos/llvm-package-windows#2]
Hi,
nice find..
would be nice if you can provide also some master branch (9.0) builds..
even with low frequency updates like monthly or similar, similar to:
https://llvm.org/builds/
but including complete LLVM tools as your packages include: like llvm-as,llvm-dis,etc..
interesting in testing clang HIP now that AMD driver includes amdhip64 library but seems "clang++ -x hip " fails because needs llvm-link which is missing in https://llvm.org/builds/ package..
thanks..

**Comment by oscarbg** [comment]
Forgot to say do you support AMDGPU target?
also I ask about LLVM&Clang 9.0 because of more mature clang HIP backend and also because clang 8.0 has problems parsing VS2019 headers(?)

**Comment by oscarbg** [comment]
sadly seems you do not provide AMDGPU enabled builds as using your llvm-link and llc I get error:
```
"e:\\llvm9july\\bin\\llc" "C:\\Users\\rtfss\\AppData\\Local\\Temp\\square.hipref-hip-amdgcn-amd-amdhsa-gfx900-gfx900-optimized-6a2f57.bc" -mtriple=amdgcn-amd-amdhsa -filetype=obj -mcpu=gfx900 -o "C:\\Users\\rtfss\\AppData\\Local\\Temp\\square.hipref-hip-amdgcn-amd-amdhsa-gfx900-gfx900-f4f28f.o"
e:\llvm9july\bin\llc.exe: error: : error: unable to get target for 'amdgcn-amd-amdhsa', see --version and --triple.
```

**Comment by vovkos** [comment]
I can add builds of the master branch from: https://github.com/llvm/llvm-project. However, adding *all* targets is unlikely -- currently, I only build the X86 target, and it still nearly hits the (already increased!) time limit: https://ci.appveyor.com/project/vovkos/llvm-package-windows/builds/24783092

**Comment by oscarbg** [comment]
thanks for giving a try.. yep, I forgot to say I’m only interested in X86 and 2 GPU targets: AMDGPU and NVPTX.. is that reasonable to ask for? also support for current Visual Studio 2019 only is enough for me..
more on AMDGPU for HIP but also NVPTX for eventually testing current Clang OpenMP GPU support..
as already said thanks..

**Comment by vovkos** [comment]
Yes, adding one or two backends will probably work. As for MSVC2019, though -- AppVeyor CI doesn't provide a build image with it. As of now, they have MSVC2010 all the way up to MSVC2017. 

That being said, LLVM 9 compiles under MSVC2017 and the resulting binaries should (in theory) be compatible with MSVC2019.

**Comment by oscarbg** [comment]
thanks.. forget the VS2019 request then.. as you say VS2017 libs are OK for using on VS2019.. in that case for me personally don't need support for older VS versions..

**Comment by vovkos** [comment]
Builds of the master branch for LLVM/Clang are now available. 

Attempted building *all* targets, but alas, no luck -- builds time out, and it's not even close. So for now, only X86 and the two GPU targets, and only on Release builds.

**Comment by oscarbg** [comment]
thanks!! no problem with no additional targets..

**Comment by oscarbg** [comment]
Hi,
just in search of updated LLVM 10 builds I remembered your project but you don't provide it, right?
no pressure but are you still interested on providing new LLVM builds?
if you try an LLVM 10 build it would be nice also for some LLVM 11 prerelease build now that we are half way between 10 and 11 builds..
don't want to open a separate issue..
thanks..

**Comment by vovkos** [comment]
Hi, 

Unfortunately, it's impossible to build LLVM 10 (or even 9) on AppVeyor -- it times out every time (even with the increased time limit).  I tried excluding more and more modules from the build, but no success :(

Of course, it's always possible to build it locally, and then upload binaries to GitHub as release artifacts, but that kind of defeats the purpose of this repo... The original idea was to build everything on AppVeyor so that there is no question of trust to the source of the binaries -- it feels much safer to use it on your personal machine knowing it's coming from AppVeyor (as opposed to using binaries built who knows where)...

I'm thinking to try and patch LLVM CMake files so it's possible to build in stages (so that you can build different LLVM modules in different AppVeyor jobs), but it's quite a lot of work...

Anyway, right now the only way is to build it on your machine, sorry :(

**Comment by vovkos** [comment]
Just realized that the above statement about LLVM 9 might sound confusing (because I do have LLVM 9 binaries built off the master branch).

The thing is, the official LLVM 9 release times out. I guess, they included more stuff since the moment I was able to build it off the master branch...
