### ISSUE TITLE
LLVM build 11.0.1, please...

### ISSUE THREAD

**Issue by shinedeveloper** [vovkos/llvm-package-windows#5]
Please, please, provide also newer versions of LLVM build. Latest 11.0.1 would be greatly appreciated.

**Comment by apfeltee** [comment]
This repo is dead.

**Comment by vovkos** [comment]
Was dead for a while, yes. It wasn't possible to fit the build of recent LLVM releases into 1h 30m allotted by AppVeyor -- even after excluding everything possible and playing with different build options. And no, building locally and just uploading release artifacts wasn't even considered as a solution.

However, It looks like GitHub Actions allow 6 hours of build time per job. So I'm going to try and revive the repo! Stay tuned.

**Comment by vovkos** [comment]
Alright, we are back -- thanks to GitHub Actions and their generosity with the build timelimit for jobs :)

Here's LLVM-11.1.0: https://github.com/vovkos/llvm-package-windows/releases/llvm-11.1.0

**Comment by apfeltee** [comment]
I'm glad to stand corrected! Thank you very much.
