### ISSUE TITLE
Not really building x86 binaries?

### ISSUE THREAD

**Issue by dabrahams** [vovkos/llvm-package-windows#9]
From looking at the code, I think the things being labeled as x86 binaries are actually x64 binaries; `TARGET_CPU` doesn't get used for anything but choosing the names of files.

**Comment by vovkos** [comment]
You are right, the built binaries were all `x64`. `TARGET_CPU` is used for selecting proper CMake configure-stage options, but the `CMAKE_OPTIONS` variable was not appended to the command line. As a result, all builds starting with `llvm-13` only contained `x64` binaries. 

Rebuilt everything starting with `llvm-13` and up (including the latest-and-greatest `llvm-18.6.1`).

**Comment by dabrahams** [comment]
Thanks; I [have my own system now](https://github.com/hylo-lang/llvm-build) but haven't yet tried it with llvm-18.
